import os

# WireGuard Configuration
WIREGUARD_PATH = "/wireguard-config"
SERVER_PUBLIC_KEY_PLACEHOLDER = "SERVER_PUBLIC_KEY_PLACEHOLDER"
DOCKER_CONTAINER_NAME = "wireguard"
SERVER_CONFIG_PATH = "wg_confs/wg0.conf"
PEER_IP_RANGE = "10.0.3.0"
PEER_IP_START = 2

# Prometheus Configuration
PROMETHEUS_URL = os.getenv('PROMETHEUS_URL', 'http://192.168.43.30:9090')
PROMETHEUS_EXPORTER_URL = os.getenv('PROMETHEUS_EXPORTER_URL', 'http://192.168.43.30:9586')